services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hospital_db
      MYSQL_USER: hospital_user
      MYSQL_PASSWORD: hospital_password
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

  django-backend:
    build: ./backend
    command: sh -c "sleep 15 && python manage.py makemigrations booking && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_SECRET_KEY: change-me
      DJANGO_DEBUG: '1'
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      MYSQL_DATABASE: hospital_db
      MYSQL_USER: hospital_user
      MYSQL_PASSWORD: hospital_password
      MYSQL_HOST: db
      MYSQL_PORT: '3306'
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    depends_on:
      - db

  react-frontend:
    build: ./frontend
    environment:
      VITE_API_BASE_URL: http://host.docker.internal:8000/api/
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - django-backend

volumes:
  db_data:
